name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.x'
      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=386 go build -o lms-windows-386.exe
          GOOS=windows GOARCH=amd64 go build -o lms-windows-amd64.exe
      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=386 go build -o lms-linux-386
          GOOS=linux GOARCH=amd64 go build -o lms-linux-amd64
          GOOS=linux GOARCH=arm go build -o lms-linux-arm
          GOOS=linux GOARCH=arm64 go build -o lms-linux-arm64
      - name: Build for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o lms-darwin-amd64
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifact: lms-windows-386.exe,lms-windows-amd64.exe,lms-linux-386,lms-linux-amd64,lms-linux-arm,lms-linux-arm64,lms-darwin-386,lms-darwin-amd64
          artifactContentType: application/octet-stream
          body: 'This is release ${{ github.run_number }}.
          
            The last commit message was:
            ${{ github.event.head_commit.message }}'
          name: 'Release ${{ github.run_number }}'
          tag: 'v${{ github.run_number }}'