name: Build and Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.x'
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install p7zip-full -y
          chmod +x ./build.sh
          ./build.sh
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "output/*"
          artifactContentType: application/octet-stream
          body: 'This is release ${{ github.run_number }}.
          
            The last commit message was:
            ${{ github.event.head_commit.message }}'
          name: 'Release ${{ github.run_number }}'
          tag: 'v${{ github.run_number }}'